# Install Golang manually first - https://golang.org/dl/

- name: add Golang to systems path
  lineinfile:
    path: "{{ home_dir }}/.bashrc"
    line: PATH=$PATH:/usr/local/go/bin
    create: yes

- name: create go directory
  file:
    path: "{{ home_dir }}/go/src"
    state: directory
