# Install Golang manually first - https://golang.org/dl/

- name: add Golang settings
  lineinfile:
    path: "{{ home_dir }}/.bashrc"
    line: export GOROOT=/usr/local/go
    create: yes

- name: add Golang settings
  lineinfile:
    path: "{{ home_dir }}/.bashrc"
    line: export GOPATH=/home/nduhovnijs/go
    create: yes

- name: add Golang settings
  lineinfile:
    path: "{{ home_dir }}/.bashrc"
    line: export PATH=$GOPATH/bin:$PATH
    create: yes

- name: add Golang settings
  lineinfile:
    path: "{{ home_dir }}/.bashrc"
    line: export PATH=$PATH:$GOROOT/bin
    create: yes