- name: Install Gnome must haves
  apt: 
    name:
      - chrome-gnome-shell  # Integration with Firefox add-on
      - gnome-tweaks
  become: true

- name: Configure available keyboard layouts in Gnome
  dconf:
    key: "/org/gnome/desktop/input-sources/sources"
    value: "[('xkb', 'lv'), ('xkb', 'ru')]"
