- name: Install software via Apt
  apt: 
    name:
      - build-essential
      - curl
      - default-jre
      - git
      - mc
      - libqt5webkit5  # Needed for GlobalProtect
  become: true

- name: add local ~/bin directory (Ubuntu adds to path automatically)
  file:
    path: "{{ home_dir }}/bin"
    state: directory

- name: Disable auto-switch for Bluetooth profiles (to stay on A2DP)
  lineinfile:
    path: "/etc/pulse/default.pa"
    regexp: 'load-module module-bluetooth-policy'
    line: 'load-module module-bluetooth-policy auto_switch=0'
    create: yes
  become: true

- name: Add a script for switching between Bluetooth profiles
  copy:
    src: "{{ role_path }}/files/bluetooth_profile.sh"
    dest: "{{ home_dir }}/bin/bluetooth_profile.sh"
    mode: 0755
  become: true

  
