- apt_repository:
    repo: ppa:linuxuprising/guake
  become: yes

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
  become: yes

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
    force_apt_get: yes
  become: yes

- name: Install 1st party software (via Apt)
  apt: 
    name:
      - curl
      - guake # Toggle terminal by F12 key
      - libsnmp-dev
      - python3-distutils
      - python3-pip
      - python3-virtualenv
      # - mc
      # - pass  # Command line tool to store few passwords (unlocked by Gnome) - commenting out (was needed for openconnect)
  become: true

- name: Install 3rd party software (via Snap Stable)
  snap:
    name:
      # Manually install Google Chrome
      # Manually install Microsoft Teams
      # Manually install Slack
      - onlyoffice-desktopeditors
      - telegram-desktop
  become: yes

- name: Install 3rd party software (via Snap Edge)
  snap:
    name:
      # Manually install Google Chrome
      # Manually install Microsoft Teams
      # Manually install Slack
      - standard-notes
    channel: latest/edge
  become: yes

- name: Install 3rd party software (via Snap Classic)
  snap:
    name: 
      - code
      - pycharm-community
    classic: yes
  become: true

- name: add local /bin directory
  file:
    path: "{{ home_dir }}/bin"
    state: directory

- name: add local /bin to path
  lineinfile:
    path: "{{ home_dir }}/.bashrc"
    line: PATH=$PATH:{{ home_dir }}/bin
    create: yes